
export const Social_Icons = [
  {
    link: "https://github.com/sumitj1",
    image: "/Github.svg",
    alt: "Sumit Joshi - Github  ",
  },
  {
    link: "https://www.instagram.com/sumitj.exe",
    image: "/Instagram.svg",
    alt: "Sumit Joshi - Instagram",
  },
  {
    link: "https://www.linkedin.com/in/sumitjoshi181",
    image: "/LinkedIn.svg",
    alt: "Sumit Joshi - LinkedIn",
  },
];

export const Projects_List = [
  {
    link: "https://www.herofincorp.com/",
    image: "/projects/herofincorp.png",
    alt: "herofincorp",
    title: "Hero FinCorp",
    description:
      "Provide financial solution that match your needs and help you build a better future.",
    class: "from-green-500 to-green-300",
  },
  {
    link: "https://greenaider.com/",
    image: "/projects/greenaider.png",
    alt: "greenaider",
    title: "Greenaider",
    description:
      "Greenaider empowers organizations of all sizes and their people to achieve net zero emissions faster.",
    class: "from-blue-500 to-blue-200",
  },
  {
    link: "http://18.189.96.178:8383/merchant/",
    image: "/projects/klikidyPay.png",
    alt: "klikidyPay",
    title: "Klikidy Pay",
    description:
      "",
    class: "from-yellow-500 to-yellow-200",
  },
  {
    link: "http://159.89.234.66:9051",
    image: "/projects/weater-coop.png",
    alt: "weater-coop",
    title: "Weather Co-op",
    description:
      "",
    class: "from-teal-400 to-teal-200",
  }
];

export const Certifications_List = [
  {
    link: "https://udemy-certificate.s3.amazonaws.com/image/UC-67e61a1f-0b4f-4cf8-83eb-a575563f14ff.jpg?v=1680785959000",
    image: "/certifications/nextjs-developer.jpg",
  },
];

export const Experience_List = [
  {
    link: "https://www.dgliger.co.in/",
    companyName: "DGLiger",
    designation: "Frontend Developer",
    location: "Gurugram",
    date: "May 2024 - Present",
    description:
      "Currently, I am building and refining user interfaces by transforming UI/UX designs into responsive and high-performance web applications. I am optimizing applications for speed, enhancing SEO rankings, and ensuring a seamless user experience. I am also integrating the latest libraries and web APIs to keep the applications modern, secure, and scalable.",
    technologies: ["Next.js", "React", "JavaScript", "Redux"],
  },
  {
    link: "https://otssolutions.com/",
    companyName: "OTS Solutions",
    designation: "Full Stack Developer",
    location: "Gurugram",
    date: "August 2021 - May 2024",
    description:
      "I designed and developed scalable, maintainable web applications using modern frontend frameworks like Angular, along with HTML, CSS, and JavaScript. I built RESTful APIs with mysql and MongoDB, ensuring high performance, security, and reliability. I integrated third-party libraries and services, collaborated with cross-functional teams to deliver end-to-end solutions, and troubleshot issues across the entire technology stack to maintain smooth application operation.",
    technologies: ["React", "Angular", "JavaScript", "mysql", "MongoDB"],
  },
  {
    link: "https://www.itechmission.org/",
    companyName: "iTech Mission",
    designation: "Full Stack Developer",
    location: "New Delhi",
    date: "July 2020 - July 2021",
    description:
      "I collaborated with senior engineers to design, develop, and maintain web applications using the MEAN stack (MongoDB, Express.js, Angular, React, Node.js). I assisted in building RESTful APIs with Node.js and Express.js to ensure scalability, security, and performance. I participated in developing responsive and intuitive user interfaces using Angular, HTML, and CSS. I contributed to integrating third-party libraries and services under the guidance of senior engineers and assisted in troubleshooting and debugging issues across the entire technology stack.",
    technologies: ["React", "Angular", "JavaScript", "Node.js", "MongoDB"],
  },
];


export const Skills_List = [
  {
    name : "HTML",
    image: "/logo/html.svg",
    width : 80,
    height : 80,
    alt: "HTML",
    class: "from-purple-700 to-orange-500",
  },
  {
    name : "CSS",
    image: "/logo/css.svg",
    width : 80,
    height : 80,
    alt: "CSS",
    class: "from-purple-700 to-blue-500",
  },
  {
    name : "Tailwind",
    image: "/logo/tailwind.svg",
    width : 80,
    height : 80,
    alt: "Tailwind",
    class: "from-teal-400 to-blue-500",
  },
  {
    name : "",
    image: "/logo/sass.svg",
    width : 80,
    height : 80,
    alt: "Sass",
    class: "",
  },
  {
    name : "",
    image: "/logo/npm.svg",
    width : 80,
    height : 80,
    alt: "npm",
    class: "from-red-500 to-pink-500",
  },
  {
    name : "Yarn",
    image: "/logo/yarn.svg",
    width : 70,
    height : 70,
    alt: "yarn",
    class: "from-blue-600 to-cyan-500",
  },
  {
    name : "Vite",
    image: "/logo/vite.svg",
    width : 70,
    height : 70,
    alt: "vite",
    class: "from-yellow-400 to-purple-500",
  },
  {
    name : "MUI",
    image: "/logo/mui.svg",
    width : 70,
    height : 70,
    alt: "mui",
    class: "from-blue-400 to-blue-600 w-100",
  },
  {
    name : "PrimeNG",
    image: "/logo/primeng.svg",
    width : 70,
    height : 70,
    alt: "primeng",
    class: "from-red-500 to-orange-500",
  },
  {
    name : "PrimeReact",
    image: "/logo/primereact.svg",
    width : 70,
    height : 70,
    alt: "primereact",
    class: "from-blue-500 to-teal-500",
  },
  {
    name : "Shadcn UI",
    image: "/logo/shadcn-ui.svg",
    width : 70,
    height : 70,
    alt: "shadcn-ui",
    class: "from-gray-600 to-gray-800",
  },
  {
    name : "Chart.js",
    image: "/logo/chartjs.svg",
    width : 70,
    height : 70,
    alt: "chartjs",
    class: "from-orange-500 to-red-700",
  },
  {
    name : "Mongoose",
    image: "/logo/mongoose.svg",
    width : 70,
    height : 70,
    alt: "mongoose",
    class: "from-red-600 to-orange-500",
  },
  {
    name : "VS Code",
    image: "/logo/vscode.svg",
    width : 70,
    height : 70,
    alt: "vscode",
    class: "from-blue-500 to-indigo-500",
  },
  {
    name : "Typescript",
    image: "/logo/typescript.svg",
    width : 70,
    height : 70,
    alt: "typescript",
    class: "from-blue-600 to-blue-400",
  },
  {
    name : "twilio",
    image: "/logo/twilio.svg",
    width : 70,
    height : 70,
    alt: "Twilio",
    class: "from-red-500 to-red-700",
  },
  {
    name : "",
    image: "/logo/stripe.svg",
    width : 70,
    height : 70,
    alt: "stripe",
    class: "",
  },
  {
    name : "Strapi",
    image: "/logo/strapi-2.svg",
    width : 70,
    height : 70,
    alt: "Strapi",
    class: "from-purple-500 to-indigo-500",
  },
  {
    name : "redux",
    image: "/logo/redux.svg",
    width : 70,
    height : 70,
    alt: "redux",
    class: "from-purple-600 to-indigo-600",
  },
  {
    name : "Router",
    image: "/logo/reactrouter.svg",
    width : 90,
    height : 90,
    alt: "reactrouter",
    class: "from-red-500 to-orange-500",
  },
  {
    name : "PostgreSQL",
    image: "/logo/postgresql.svg",
    width : 70,
    height : 70,
    alt: "postgresql",
    class: "from-blue-700 to-blue-500",
  },
  {
    name : "PM2",
    image: "/logo/pm2.svg",
    width : 70,
    height : 70,
    alt: "pm2",
    class: "from-violet-500 to-violet-700",
  },
  {
    name : "Node.js",
    image: "/logo/nodejs.svg",
    width : 70,
    height : 70,
    alt: "nodejs",
    class: "from-green-500 to-green-700",
  },
  {
    name : "MySQL",
    image: "/logo/mysql.svg",
    width : 70,
    height : 70,
    alt: "mysql",
    class: "from-blue-500 to-cyan-500",
  }, {
    name : "MongoDB",
    image: "/logo/mongodb.svg",
    width : 37,
    height : 37,
    alt: "mongodb",
    class: "from-green-600 to-green-400",
  },
  {
    name : "JWT",
    image: "/logo/jwt.svg",
    width : 70,
    height : 70,
    alt: "jwt",
    class: "from-yellow-500 to-orange-500",
  },
  {
    name : "JSON",
    image: "/logo/json.svg",
    width : 70,
    height : 70,
    alt: "json",
    class: "from-gray-400 to-gray-600",
  },
  {
    name : "Highcharts",
    image: "/logo/highcharts.svg",
    width : 70,
    height : 70,
    alt: "highcharts",
    class: "from-blue-600 to-blue-400",
  },
  {
    name : "Gitlab",
    image: "/logo/gitlab.svg",
    width : 70,
    height : 70,
    alt: "gitLab",
    class: "from-orange-500 to-red-600",
  },
  {
    name : "Github",
    image: "/logo/github.svg",
    width : 70,
    height : 70,
    alt: "github",
    class: "from-gray-700 to-gray-500",
  },
  {
    name : "Git",
    image: "/logo/git.svg",
    width : 70,
    height : 70,
    alt: "git",
    class: "from-orange-500 to-red-500",
  },
  {
    name : "ExpressJS",
    image: "/logo/expressjs.svg",
    width : 70,
    height : 70,
    alt: "expressjs",
    class: "from-gray-500 to-gray-700",
  },
  {
    name : "Dotenv",
    image: "/logo/dotenv.svg",
    width : 70,
    height : 70,
    alt: "dotenv",
    class: "from-yellow-500 to-yellow-700",
  },
  {
    name : "Docker",
    image: "/logo/docker.svg",
    width : 70,
    height : 70,
    alt: "docker",
    class: "from-blue-500 to-blue-700",
  },
  {
    name : "",
    image: "/logo/axios.svg",
    width : 70,
    height : 70,
    alt: "axios",
    class: "",
  },
  {
    name : "AMP",
    image: "/logo/amp.svg",
    width : 70,
    height : 70,
    alt: "amp",
    class: "from-blue-500 to-indigo-500",
  }
]